### ISSUE TITLE
Should we allow audio file uploads?

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/rusty#100]
Currently audio media objects are allowed to be uploaded but we don't have a supported player. Should we remove this option as an upload?

**Comment by genjohnson** [comment]
We don't allow audio files to be uploaded on the service currently, so I vote we remove this option (at least for now).

**Comment by genjohnson** [comment]
We should also probably remove the option to upload videos, too.

**Comment by briand44** [comment]
Can this be closed?

**Comment by genjohnson** [comment]
Yes, I think this can be closed since #107 was merged, which removed editor/webmaster access to upload Audio & Video files. New issues can be opened for discussion about handling audio & video with oEmbed or some other solution (which may involve restoring permissions to the default File Entity types).
