### ISSUE TITLE
Prevent the deletion of the front page

### ISSUE THREAD

**Issue by genjohnson** [uiowa/rusty#113]
When deleting a node, verify that it is not set to the front page before processing the deletion. If the node is the front page, stop the deletion process and display a message instructing the user to change the front page configuration before deleting the node.

**Comment by richardbporter** [comment]
I'm ambivalent about this. Almost feels like too much. Is it a frequent problem in D7?

**Comment by genjohnson** [comment]
Every D7 site I've setup to use a basic page for the front page has ended up with an editor deleting the page before I put this check in place. I'm interested in hearing if others have had a better experience with this.

**Comment by joewhitsitt** [comment]
With basic pages becoming the homepage/landing pages instead of panels, I have been locking down the node ids through `hook_node_access()` - https://github.com/ITS-UofIowa/international.uiowa.edu/blob/master/modules/features/ip_basic_page/ip_basic_page.module#L12

I am sure there is a better way, like @genjohnson describes and would be useful.

**Comment by richardbporter** [comment]
Ok, works for me. That seems like a good route.

**Comment by genjohnson** [comment]
@joewhitsitt I don't remember which sites are using that and searching on GitHub wasn't helpful :( Sorry!

**Comment by genjohnson** [comment]
I think it was similar to your IP example, but instead of hard-coding the node ID to lock I did a vget for the front page.

**Comment by joewhitsitt** [comment]
i got a little something in the works and hope to have it up for review soon.

**Comment by genjohnson** [comment]
Closed by #124
