### ISSUE TITLE
Decide on subtheming strategy

### ISSUE THREAD

**Issue by genjohnson** [uiowa/rusty#163]
Determine a recommended inheritance structure for subtheming.

For example, how opinionated in CSS will uiowa_bootstrap be?... will it include templates and CSS, or will it only include templates?

**Comment by pyrello** [comment]
What is the goal of the uiowa_bootstrap library? Obviously, it'll set some defaults for colors based on the palette that gets selected. But what else does it provide?

**Comment by pyrello** [comment]
It would be my assumption that the UI theme library that @markahrens is working on would be included in uiowa_bootstrap. I think that having a set of baseline templates would be a good idea as a starting point. Maybe these templates would be pretty basic and just implement any required bootstrap markup.

As a separate part of the subtheming discussion, we also need to decide on how base theme assets will be provided to sub-themes. In the [bootstrap](https://www.drupal.org/project/bootstrap) project, sub-themes add in their own bootstrap assets, so any bootstrap variables or overrides that are set on the base theme are not passed to the sub-theme. It would be nice to have a way to pass UI theme elements from the base theme so that they are not overwritten. It might also be a good idea to separate the base styles into a couple different pieces so that they can be passed down or overridden depending on the needs of the sub-theme.

What makes the above tricky is that one of the benefits of including bootstrap at the sub-theme level is being able to override variables and having that compile through a workflow process (like gulp sass) to the output stylesheet. If variables are set in the base theme, I'm not sure how they could be passed into the variables of the sub-theme. Maybe the variables could be part of the UI theme library?

**Comment by richardbporter** [comment]
Moving this to https://github.com/uiowa/uiowa_bootstrap/issues/1.
