### ISSUE TITLE
paragraphs: automatically open the first body section when creating new pages

### ISSUE THREAD

**Issue by pyrello** [uiowa/rusty#196]
I'm interested in having a field on the page content type that uses the standard body field as an alternative to using the paragraph sections. This is, in part, because most content types on most of my sites use a body field and creating a migration process to channel that into a Section > Text paragraph. Additionally, for basic pages that can easily be managed by the WYSIWYG editor, the current UI for editing a Section > Text paragraph is overly complex because you have to click edit first on the Section, then again on the Text.

Any thoughts on this approach? I'm not sure exactly how it would look to the user, so I'm open to ideas about how it is presented.

**Comment by adamdelaney** [comment]
This has already been discussed and I don't believe will be implemented. See: https://github.com/uiowa/rusty/wiki/D8-Check-in-notes.

**Comment by pyrello** [comment]
Is there a plan to get the default UI to the point where a user doesn't have to click an edit button twice to be able to add to or edit the "body?"

**Comment by joewhitsitt** [comment]
i wasn't at this meeting and was only trying to implement what i could from the notes. for new pages a section/text combo is created but i haven't figured out a great way to open those two by default. open to help on that.

**Comment by adamdelaney** [comment]
@pyrello possibly, I don't think this is a 1.0.0 priority.

**Comment by richardbporter** [comment]
Yea we discussed this at length, going over advantages/disadvantages. Given that we will have to find a migration path into Section > Text for certain sites, I'd prefer to stick with the current implementation.

**Comment by joewhitsitt** [comment]
There was an issue committed to paragraphs DEVs EXPERIMENTAL field widget that allows low count paragraph items to be open even if the overall field setting is set to closed/preview.
https://www.drupal.org/project/paragraphs/issues/2577229

I tested it and set the page and section paragraph fields with a threshold of 1 so that our initial section and text items are open on form load.

Ideally we don't switch to the Experimental widget until it is production ready.

I think I read somewhere that widget settings are no longer alterable in things like form_alter... If that is the case and we have to wait, maybe we have the default edit mode be open and hope people don't go nuts with paragraph items from the get go?

**Comment by richardbporter** [comment]
https://github.com/uiowa/rusty/commit/197d4ce21b160114203397ff411f2db20a0c3cc8#diff-8dc998297e2fb3b5a273ec4ed9476205
